package vista;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author JHONATAN
 */
public class ListaClientes extends javax.swing.JInternalFrame {

    /**
     * Creates new form ListaClientes
     */
    public ListaClientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setResizable(true);
        setTitle("Lista de clientes");
        setMinimumSize(new java.awt.Dimension(600, 380));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setFont(new java.awt.Font("Hack Nerd Font Mono", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Jorge", "Manuel Navarro", "jorge@gmail.com"},
                {"Elizabeth", "Sauceda", "elizabeth@gmail.com"},
                {"Emiliano", "Pineda Ferrer", "emiliano@gmail.com"},
                {"Luis", "Cuellas Tello", "luis@gmail.com"},
                {"Catalina", "Zamudio Mata", "catalina@gmail.com"},
                {"Maria", "Jimenez Benitez", "maria@outlook.com"},
                {"Jesus", "Vicente Velazco", "jesus@hootmail.com"},
                {"Sebastian", "Villareal Posada", "sebastian@gmail.com"},
                {"Esteban", "Fierro Chacon", "esteban@hotmail.com"},
                {"Sofia", "Echevarria Aguirre", "sofia@gmail.com"},
                {"Gabriel ", "Briseño Enriquez", "gariel@outlook.com"},
                {"Simon", "Venegas Resendez", "simon@gmail.com"},
                {"Catalina", "Salazar Galindo", "catalina@hotmail.com"},
                {"Franco", "Porras Benavides", "franco@outlook.com"},
                {"Esteban", "Amador Sevilla", "esteban@outlook.com"},
                {"Jesus", "Vicente Velazco", "jesus@hootmail.com"},
                {"Sofia", "Echevarria Aguirre", "sofia@gmail.com"},
                {"Luis", "Cuellas Tello", "luis@gmail.com"},
                {"Elizabeth", "Sauceda", "elizabeth@gmail.com"},
                {"Gabriel ", "Briseño Enriquez", "gariel@outlook.com"},
                {"Catalina", "Salazar Galindo", "catalina@hotmail.com"},
                {"Esteban", "Amador Sevilla", "esteban@outlook.com"},
                {"Sebastian", "Villareal Posada", "sebastian@gmail.com"},
                {"Maria", "Jimenez Benitez", "maria@outlook.com"},
                {"Catalina", "Zamudio Mata", "catalina@gmail.com"}
            },
            new String [] {
                "Nombres", "Apellidos", "Correo"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 510, 250));

        jLabel1.setFont(new java.awt.Font("Hack Nerd Font Mono", 1, 24)); // NOI18N
        jLabel1.setText("CLIENTES");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
